from distutils.core import setup
setup(
  name = 'dialogflow webhook json',         
  packages = ['df_webhook_json'], 
  version = '1.0.0',      
  license='MIT',      
  description = 'Create webhook JSON responses directly using this library',   
  author = 'Pragnakalp Techlabs',                   
  author_email = 'letstalk@pragnakalp.com',      
  url = 'https://github.com/pragnakalp/dialogflow-webhook-response-libary-in-python',  
  download_url = 'https://github.com/pragnakalp/dialogflow-webhook-response-libary-in-python/archive/v_01.tar.gz',    
  keywords = ['dialogflow', 'actions-on-google', 'messenger', 'webhook', 'webhook json'],   
  install_requires=[],
  classifiers=[
    'Development Status :: 4 - Beta',      
    'Intended Audience :: Developers',      
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',   
    'Programming Language :: Python :: 3',      
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
  ],
)